# Generated by Django 2.2.2 on 2019-11-22 05:05

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_video_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos/', validators=[home.models.file_size], verbose_name=''),
        ),
    ]
